male(Edwin Michael)
female(Alice Paula)
male(Martin Smith)
female(Elna Jefferson)
male(Martin Smith)
female(Kerstina Hansdotter)
male(Gustaf Smith)
female(Anna Hansdotter)
female(Kirsti Marie)
female(Astrid Shermanna)
male(Hjalmar Smith)
male(Hjalmar Smith)
male(Gus Smith)
male(Carl Emil)
male(Hans Peter)
male(Edwin Willard)
male(Herman Julius)
male(John Hjalmar)
female(Marjorie Lee)
female(Evelyn Michaels)
female(Jennifer Anderson)
female(Lillie Harriet)
male(Magnes Smith)
male(Emil Smith)
female(Anna Streiffert)
female(Hanna Smith)
female(Ingar Smith)
male(Ingeman Smith)
female(Marjorie Alice)
male(Lloyd Smith)
female(Janis Elaine)
male(Eric Lloyd)
male(Keith Lloyd)
male(Craig Peter)
male(Lars Peter)
female(Darcy Horne)
male(Ingeman Smith)
female(Marta Ericsdotter)
female(Marjorie Ohman)
female(Janice Ann)
female(Amber Marie)
male(Mason Michael)
male(Charles Neilsen)
mother(Janice Ann, Mason Michael)
mother(Janice Ann, Amber Marie)
father(Edwin Michael, Mason Michael)
father(Edwin Michael, Amber Marie)
mother(Alice Paula, Marjorie Alice)
mother(Alice Paula, Edwin Michael)
father(John Hjalmar, Marjorie Alice)
father(John Hjalmar, Edwin Michael)
mother(Elna Jefferson, Hanna Smith)
mother(Elna Jefferson, Ingar Smith)
mother(Elna Jefferson, Ingeman Smith)
mother(Elna Jefferson, Martin Smith)
father(Martin Smith, Hanna Smith)
father(Martin Smith, Ingar Smith)
father(Martin Smith, Ingeman Smith)
father(Martin Smith, Martin Smith)
mother(Marta Ericsdotter, Martin Smith)
father(Ingeman Smith, Martin Smith)
mother(Kerstina Hansdotter, Magnes Smith)
mother(Kerstina Hansdotter, Emil Smith)
mother(Kerstina Hansdotter, Gustaf Smith)
father(Martin Smith, Magnes Smith)
father(Martin Smith, Emil Smith)
father(Martin Smith, Gustaf Smith)
mother(Anna Hansdotter, Kirsti Marie)
mother(Anna Hansdotter, Astrid Shermanna)
mother(Anna Hansdotter, Hjalmar Smith)
mother(Anna Hansdotter, Hjalmar Smith)
mother(Anna Hansdotter, Gus Smith)
mother(Anna Hansdotter, Carl Emil)
mother(Anna Hansdotter, Hans Peter)
father(Gustaf Smith, Kirsti Marie)
father(Gustaf Smith, Astrid Shermanna)
father(Gustaf Smith, Hjalmar Smith)
father(Gustaf Smith, Hjalmar Smith)
father(Gustaf Smith, Gus Smith)
father(Gustaf Smith, Carl Emil)
father(Gustaf Smith, Hans Peter)
mother(Marjorie Ohman, John Hjalmar)
mother(Marjorie Ohman, Marjorie Lee)
father(Hjalmar Smith, John Hjalmar)
father(Hjalmar Smith, Marjorie Lee)
mother(Lillie Harriet, Lloyd Smith)
father(Hans Peter, Lloyd Smith)
mother(Janis Elaine, Eric Lloyd)
mother(Janis Elaine, Keith Lloyd)
mother(Janis Elaine, Craig Peter)
father(Lloyd Smith, Eric Lloyd)
father(Lloyd Smith, Keith Lloyd)
father(Lloyd Smith, Craig Peter)
mother(Darcy Horne, Lars Peter)
father(Eric Lloyd, Lars Peter)
